spring:
  datasource:
    #url: jdbc:h2:mem:the_engine_shop_DB
    #username: dino
    driver-class-name: org.postgresql.Driver
    password: pizzacalabresa
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      properties:
        hibernate.format_sql: true
      ddl-auto: create
  #h2:
    #console:
      #enabled: true
      #path: /h2-console
      #settings:
        #trace: false
        #web-allow-others: false
