-- noinspection SqlNoDataSourceInspectionForFile

CREATE TABLE motores
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    engine_number   UUID                                    NOT NULL,
    price           DECIMAL                                 NOT NULL,
    manufacturer    VARCHAR(255)                            NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    nomination_code VARCHAR(255)                            NOT NULL,
    liter           DECIMAL                                 NOT NULL,
    cylinder        INT                                     NOT NULL,
    valves          INT                                     NOT NULL,
    fuel            VARCHAR(255)                            NOT NULL,
    status          SMALLINT,
    customer_id     BIGINT,
    CONSTRAINT pk_motores PRIMARY KEY (id)
);

ALTER TABLE motores
    ADD CONSTRAINT uc_motores_engine_number UNIQUE (engine_number);

ALTER TABLE motores
    ADD CONSTRAINT FK_MOTORES_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES cliente (id);